### ISSUE TITLE
[課題] 221030

### ISSUE THREAD

**Issue by technicakidz** [Ayaka-Nichols/my-first-blog#14]
### ToDo

- [x] オリジナル機能のアイデア出し(issue コメントでOK)
   - 理想の機能
   - 調査込みの実現難易度相談アイデア
- [x] チュートリアル応用パートの issue 化(Homework 3つ分)

**Comment by Ayaka-Nichols** [comment]
## オリジナル機能のアイデア出し

Random Meal Generator(https://huirayj.github.io/random-meal-generator/)
Github(https://github.com/huirayj/random-meal-generator)
献立をランダムで提案してくれる	

<br>

### ▼理想の機能

- Breakfast, Lunch, Dinnerで分かれている
　参考サイト：
<br>http://www.dammitwhatdoyouwant.co.uk/

- 各SNSでシェアする機能
　参考サイト：
<br>http://www.dammitwhatdoyouwant.co.uk/

- お気に入り献立を登録する機能
　参考サイト：
<br>https://huirayj.github.io/random-meal-generator/%EF%BC%89
<br>https://github.com/huirayj/random-meal-generator
***
### ▼調査込みの実現難易度相談アイデア
- ランダムな料理サイト/料理を表示する機能
<br>パブリックAPIを使う？
<br>参考サイト：
<br>http://www.dammitwhatdoyouwant.co.uk/
<br>https://github.com/huirayj/random-meal-generator
<br>https://www.themealdb.com/

**Comment by technicakidz** [comment]
### オリジナルアプリのアイデア出しメモ

- アプリを考えるときの観点は主に2つ
  1. あったらいいな(理想状態の定義)
  1. 実現可能性
- アプリのアイデア出しは一番開発のモチベーション、アプリの「意味」を確立しやすいフェーズ
- スケールできる状態に要件定義することは重要
- 一方で、あれもこれもな機能追加になることは避けたい

**Comment by Ayaka-Nichols** [comment]
### 用途
忙しい現代人に代わって今日のご飯を提案してくれる。時短。

### ゴール
ユーザーは他のタスクに時間を使うことができる。

**Comment by technicakidz** [comment]
ポートフォリオサイトの雛形まで作成完了，オリジナルアプリのデザインカンプを作成中．
