### ISSUE TITLE
[課題] Django Girls Tutorial: Extensions - 宿題: ウェブサイトにもっと機能を追加しよう!

### ISSUE THREAD

**Issue by Ayaka-Nichols** [Ayaka-Nichols/my-first-blog#15]
### 概要
***
- あたらしい記事を草稿として保存する
- 掲載ボタンをつける
- 削除ボタンを作る

### 得たこと
***
1. blog/views.py の post_new 関数と post_edit 関数にある下の行を削除する

<br>〈blog/views.py〉
```
post.published_date = timezone.now()
```
<br> こうすると新しい記事は草稿として保存される。

2. 草稿の一覧ページを作る
<br>- blog/templates/blog/base.html のヘッダーにリンクを追加する
<br>〈blog/templates/blog/base.html〉
```
<a href="{% url 'post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
```

<br>-  blog/urls.py にurlを追加する
<br>〈blog/urls.py〉
```
path('drafts/', views.post_draft_list, name='post_draft_list'),
```
<br>-  blog/views.py にビューを作る
<br>〈blog/views.py〉
```
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})
```

<br>- テンプレートの作成をする。blog/templates/blog/post_draft_list.html を作成して、下の記述を加える。
<br>〈blog/templates/blog/post_draft_list.html〉
```
{% extends 'blog/base.html' %}
 
{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}
```

<br>- [http://127.0.0.1:8000/drafts/を開く](http://127.0.0.1:8000/drafts/%E3%82%92%E9%96%8B%E3%81%8F)

3. 掲載ボタンをつける
<br>- blog/templates/blog/post_detail.html の下記を
```
{% if post.published_date %}
  <div class="date">
  {{ post.published_date }}
 </div>
{% endif %}
```
<br>下記に書き換える
```
	​{% if post.published_date %}
   	 <div class="date">
       	 {{ post.published_date }}
   	</div>
{% else %}
    	<a class="btn btn-default" href="{% url 'post_publish' pk=post.pk %}">Publish</a>
{% endif %}
```
<br>- 新しいURLを追加する
<br>〈blog/urls.py 〉
```
path('post/<pk>/publish/', views.post_publish, name='post_publish'),
```
<br>- 最後に ビュー を追加する
<br>〈blog/views.py〉
```
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)
```
4. 記事の削除ボタンを作る
<br>- blog/templates/blog/post_detail.html に、下の行を追加する（編集ボタンの行の直後に）
<br>〈blog/templates/blog/post_detail.html〉
```
<a class="btn btn-default" href="{% url 'post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
```
<br>- URLの作成
<br>〈blog/urls.py〉
```
path('post/<pk>/remove/', views.post_remove, name='post_remove'),
```
<br>- ビューの作成
<br>〈blog/views.py〉
```
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post_list')
```

### 難しかったこと
***
草稿一覧ページを作成後 http://127.0.0.1:8000/drafts/ を開くと404エラーが出た。
Djangogirls Extentionのコードが間違っているみたいだったので、
DjangogirlsのGithub (https://github.com/DjangoGirls/tutorial-extensions/blob/master/en/homework/README.md )を参考にしたら、404エラーが消えた。（その他に間違ったコードが書かれている箇所があった）。

### 解決できなかったこと
***
なし

**Comment by technicakidz** [comment]
LGTM！
