### ISSUE TITLE
課題「DjangoのORMとクエリセット」

### ISSUE THREAD

**Issue by technicakidz** [Ayaka-Nichols/my-first-blog#3]
https://tutorial.djangogirls.org/ja/django_orm/

**Comment by technicakidz** [comment]
TODO: 学習memoをコメントに記載する

**Comment by Ayaka-Nichols** [comment]
### クエリセット
***
モデルのオブジェクトのリストのこと。モデルから取り出した一連の情報。

### ORM
***
Object-Relational Mapping"。
データベースとプログラミング言語観のオブジェクトを返還するプログラミング技法。
データベースとオブジェクト指向プログラミング言語の間の非互換なデータを変換するプログラミング技法。
ORMを使えば、アプリケーションのモデルとデータベースのテーブルのマッピングさえしてあげればSQL文を書かなくてもデータベースの操作ができるようになる。

### Django Shell
***
Djangoアプリケーションの環境を有効にした状態で、Pythonのコードをひとつずつ実行できるコマンドツール。

1. Django Shellを起動する
〈Command-Line〉
```
python manage.py shell
```
→＞＞＞という表示に変わる
→manage.py はサーバーを動かしたり、アプリを作成するために必要なファイル

2. Djangoの管理画面から、作ったポストのリストを表示させてみる

　blog.modelsからPostモデルをダウンロード
〈Command-Line〉
```
>>>from blog.models import Post
```
　Post. objects.all()を実行
〈Command-Line〉
```
>>>Post. objects. all()
```
→ <QuerySet[<Post:日記1>],[<Post:日記2>],[<Post:日記3>],[<Post:日記4>],[<Post:日記5>]というオブジェクトが表示される。[<Post:日記1>],[<Post:日記2>],[<Post:日記3>],[<Post:日記4>],[<Post:日記5>]の部分はは配列。

3. コンソール画面から新たなポストを作る

　Userモデルを先にインポートしておく。
　作成しておいたスーパーユーザー（Ayaka）を取り出す
〈Command-Line〉
```
>>> from django.contrib.auth.models import User
>>>User.objects .all()
```
→<QuerySet[<User; Ayaka>]>が表示される
```
>>>me = User.objects.get(username='Ayaka")
```
→スーパーユーザーを取り出してみる

　コンソール画面からポストを作成する
〈Command-Line〉
```
>>>Post.objects.create(author=me, title='Sample title, text='Test')
```
→<Post: Sample title>が作成される
→さらに投稿を続ける場合はこのコマンドを使う

ちゃんとポストが作成できているか確認する
〈Command-Line〉
```
>>>Post.objects.all()
```
→すべてのポスト<QuerySet[<Post:日記1>],[<Post:日記2>]～<Post: Sample title>]が表示される
　
4. オブジェクトの抽出
　
　Ayakaのポストだけ取り出したい場合
〈Command-Line〉
```
>>>(author=me)
```

　titleフィールドいtitleという単語が含まれているポストだけ取り出したい場合
〈Command-Line〉
```
>>>Post.objects.filiter(title__contains='title')
```
→アンダーバーが二個続いているのは、DjangoのORMの構文である。もしアンダーバーが一個だけだとtitle-containsというフィールド名だと判断されてしまいエラーになる。

　公開済みの全ポストだけ取り出したい場合
〈Command-Line〉
```
>>>Post.objects.filter(published_date__lte=timezone.now())
```
→lteはless than or equal to。publish_date ≦ 現在時刻となる。現在時刻とりも前、もしくは現時刻と一致した場合は抽出するということ。

5. オブジェクトのリストの並び替えをする
〈Command-Line〉
```
>>>Post.objects.order_by('created_date')
```
6. 逆順（新しく追加した順）に並び替える
〈Command-Line〉
```
>>>Post.objects.order_by('-created_date')
```
7. メソッドチェーンによる複雑なクエリ
〈Command-Line〉
```
>>>Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
```
→つなげることで、メソッドの返すクエリセットを組み合わせることができる
→Django Shellを閉じる際は>>>exit()を実行

**Comment by technicakidz** [comment]
LGTMです！
